In [30]:
import pandas as pd
import numpy as np
import Recommenders as Recommenders

In [31]:
import os  
path = os.path.abspath(r'D:\College Work\6 SEM\Minor Project\triplets_file.csv')
f = open(path)
print(f)

<_io.TextIOWrapper name='D:\\College Work\\6 SEM\\Minor Project\\triplets_file.csv' mode='r' encoding='cp1252'>

In [32]:
song_df_1 = pd.read_csv(r'D:\College Work\6 SEM\Minor Project\triplets_file.csv')
song_df_1.head()

                                    user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1

In [33]:
import os  
path = os.path.abspath(r'D:\College Work\6 SEM\Minor Project\song_data.csv')
f = open(path)
print(f)

<_io.TextIOWrapper name='D:\\College Work\\6 SEM\\Minor Project\\song_data.csv' mode='r' encoding='cp1252'>

In [34]:
song_df_2 = pd.read_csv(r'D:\College Work\6 SEM\Minor Project\song_data.csv')
song_df_2.head()

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster,2003
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteill�,Karkkiautomaatti,1995
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006
3,SOBNYVR12A8C13558C,Si Vos Quer�s,De Culo,Yerba Brava,2003
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0

In [35]:
song_df = pd.merge(song_df_1, song_df_2.drop_duplicates(['song_id']), on='song_id', how='left')
song_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Ni�os,Paco De Lucia,1976
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999

In [36]:
print(len(song_df_1), len(song_df_2))

2000000 1000000

In [40]:
## Data Pre Processing

In [42]:
song_df['song'] = song_df['title']+' - '+song_df['artist_name']
song_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year,song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0,The Cove - Jack Johnson
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Ni�os,Paco De Lucia,1976,Entre Dos Aguas - Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007,Stronger - Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005,Constellations - Jack Johnson
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999,Learn To Fly - Foo Fighters

In [43]:
song_df = song_df.head(10000)

In [44]:
song_grouped = song_df.groupby(['song']).agg({'listen_count':'count'}).reset_index()
song_grouped.head()

                                    song  listen_count
0               #40 - DAVE MATTHEWS BAND             1
1                    & Down - Boys Noize             4
2            '97 Bonnie & Clyde - Eminem             2
3          'Round Midnight - Miles Davis             3
4  'Till I Collapse - Eminem / Nate Dogg             6

In [45]:
grouped_sum = song_grouped['listen_count'].sum()
song_grouped['percentage'] = (song_grouped['listen_count'] / grouped_sum ) * 100
song_grouped.sort_values(['listen_count', 'song'], ascending=[0,1])

,song,listen_count,percentage
3660,Sehr kosmisch - Harmonia,45,0.45
4678,Undo - Bj�rk,32,0.32
5105,You're The One - Dwight Yoakam,32,0.32
1071,Dog Days Are Over (Radio Edit) - Florence + Th...,28,0.28
3655,Secrets - OneRepublic,28,0.28
...,...,...,...
5139,high fives - Four Tet,1,0.01
5140,in white rooms - Booka Shade,1,0.01
5143,paranoid android - Christopher O'Riley,1,0.01
5149,�Lo Ves? [Piano Y Voz] - Alejandro Sanz,1,0.01
5150,�poca - Gotan Project,1,0.01

In [46]:
## Popularity Recommendation

In [47]:
pr = Recommenders.popularity_recommender_py()

In [48]:
pr.create(song_df, 'user_id', 'song')

In [49]:
pr.recommend(song_df['user_id'][5])

,user_id,song,score,Rank
3660,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Sehr kosmisch - Harmonia,45,1.0
4678,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Undo - Bj�rk,32,2.0
5105,b80344d063b5ccb3212f76538f3d9e43d87dca9e,You're The One - Dwight Yoakam,32,3.0
1071,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Dog Days Are Over (Radio Edit) - Florence + Th...,28,4.0
3655,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Secrets - OneRepublic,28,5.0
4379,b80344d063b5ccb3212f76538f3d9e43d87dca9e,The Scientist - Coldplay,27,6.0
4712,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Use Somebody - Kings Of Leon,27,7.0
3476,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Revelry - Kings Of Leon,26,8.0
1387,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Fireflies - Charttraxx Karaoke,24,9.0
1862,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Horn Concerto No. 4 in E flat K495: II. Romanc...,23,10.0

In [50]:
## Item Similarity Engine

In [51]:
ir = Recommenders.item_similarity_recommender_py()
ir.create(song_df, 'user_id', 'song')

In [69]:
user_items = ir.get_user_items(song_df['user_id'][2100])

In [70]:
for user_item in user_items:
    print(user_item)

You And Me Jesus - Jake Hess
Natural's Not In It - Gang Of Four
100� - Shout Out Louds
Recess - Muse
Undo - Bj�rk
Losing Touch - The Killers
Olio - The Rapture
Dog Days Are Over (Radio Edit) - Florence + The Machine
All We Are - OneRepublic
Lovely Head - Goldfrapp
Missing Persons 1 & 2 - OneRepublic
Decades Of Despair - Carnal Forge
Us V Them - LCD Soundsystem
Dragon Queen - Yeah Yeah Yeahs
U.R.A Fever - The Kills
Tones Of Home - Blind Melon
Don't Leave Me - The All-American Rejects
Attention - The Raconteurs
Christmas Is My Favorite Time Of The Year - Kenny Rogers
Lonesome Loser - Little River Band
Lost In The Plot - The Dears
If I Can't Have You - Yvonne Elliman
She Had The World (Album Version) - Panic At The Disco
House Of Jealous Lovers - The Rapture
Dub On My Mind Dub - King Tubby
Big Munny - Swizz Beatz
Silent Shout - The Knife
Middle Of Nowhere (Album Version) - Hot Hot Heat
Flagpole Sitta - Harvey Danger
Hold On - Hot Chip
Tive Sim - Cartola
Top Of The World - The All-American Rejects
Sehr kosmisch - Harmonia
Hitched - The Kills
I Want You Back - Shione Yukawa
Destination Calabria - Alex Gaudino Feat. Crystal Waters
Feels So Good (Remastered Single Version) - Van Halen
Anybody Wanna Take Me Home - Ryan Adams
Demasiado Bueno - Edgar Oceransky
Palm Reader - Third Eye Blind
Love And War (11/11/46) (Album Version) - Rilo Kiley
Twilight Galaxy - Metric
Money Straight (Explicit Album Version) - Plies
Carry Me In Your Dreams (Albania) - Kejsi Tola
We Share Our Mothers' Health (Album Version) - The Knife
A Man/Me/Then Jim (Album Version) - Rilo Kiley
Drive Away - The All-American Rejects
Hazy Shade Of Winter - Bangles
Freak Train - Kurt Vile
Superstition - The Kills
Lewis Takes Off His Shirt - Owen Pallett
Get Down Tonight - KC And The Sunshine Band
On Bended Knee - Boyz II Men
Girl U Want (Live) - Devo
Someone's Missing - MGMT
Innocent When You Dream (78) - Tom Waits
Black Mission Goggles - Man Man
Don't Be On With Her - Miami Horror
Who Am I - Timbaland & Magoo
Mrs Thompson - The Kooks
Lost - Katy Perry
Tired Of Being Sorry - Enrique Iglesias
Signs - Tesla
All Men Are Liars - Nick Lowe
Bulletproof - La Roux
Live And Let Die - Guns N' Roses
Irreplaceable - Beyonc�
Beautiful Friday - Andru Donalds
Talk Me Out Of Tampa - Joe Nichols
Don't Leave - Faithless
Heaven Must Be Missing An Angel - Tavares
Whistle For Will - Hot Chip
Again Again - Lady GaGa
Darkness - Third Eye Blind
Back Porch - The Presidents of the United States of America
I Heard Love Is Blind - Amy Winehouse
Lookin' Out My Back Door - Creedence Clearwater Revival
Goodnight Bad Morning - The Kills
Get Innocuous! - LCD Soundsystem
Black And White - The dB's
Addicted - Amy Winehouse
White Heat - John Waite
Frases Mudas - Mikel Erentxun
Pull - Blind Melon
One Way Ticket [Radio Edit] - The Darkness
Sometimes - Miami Horror
That's That - Cass McCombs
The Runner - Kings Of Leon
We Don't Stop (Explicit) - Young Bleed
In Person - The Pussycat Dolls
Jam 4 U - Redman
Touch Too Much - Hot Chip
Don't Dance - Hot Chip
Shake A Tail Feather - The Cheetah Girls
Q-Ball - Brotha Lynch Hung
Only This Moment (R�yksopps Forsiktige Massasje) - R�yksopp
Galang - M.I.A.
Lady (Hear Me Tonight) - Modjo
Wrestlers - Hot Chip
Spaceman - The Killers
Helen Of Troy - Telefon Tel Aviv
The Only Difference Between Martyrdom and Suicide Is Press Coverage (Tommie Sunshine Brooklyn Fire Remix) - Panic! At The Disco
No Good 4 You - Cherise
This Is Your Life - The Killers
Bubble Toes - Jack Johnson
Smothered (Album Version) - Spineshank
Revelry - Kings Of Leon
Teenage Crush - Tommy Sands
Little Of Your Time - Maroon 5
Bellevue - Miami Horror
I'm Sleeping In A Submarine - Arcade Fire
Don't Know What You Got (Till It's Gone) - Cinderella
Bette Davis Eyes - Kim Carnes
Do You Remember - Moose
Hey Sexy Lady - Shaggy / Brian & Tony Gold
Nitpickin' - Danny Gatton
Rocket - Goldfrapp
Southtown (2006 Remastered LP Version) - P.O.D.
Epilogue - Asia 2001
If Looks Could Kill - Camera Obscura
Girls_ Girls_ Girls - M�tley Cr�e
Not In Love - Crystal Castles
Dreams-Come-True-Girl - Cass McCombs feat. Karen Black
I Believe In A Thing Called Love - The Darkness
Half Mast - Empire Of The Sun
There will be a happy meeting in Glory - Joseph Spence
Your Star - The All-American Rejects
Ain't Misbehavin - Sam Cooke
Brand New Key - Melanie
Product Man - Swizz Beatz
Kid - Amos Lee
What's Your Name - Future Loop Foundation
Song For Dan Treacy - MGMT
Alala (Album) - CSS
War - Chikita Violenta
From Off To On - The Knife
Age Of Consent - New Order
You Don't Know Me (featuring Regina Spektor) - Ben Folds
Five Vicodin Chased With A Shot Of Clarity (Album Version) - Atreyu
It Wasn't Me - Shaggy / Ricardo Ducent
Mayday!!! - Flobots
It's Oh So Quiet - Bj�rk
Just Got To Be - The Black Keys
Goodbye_ Apathy - OneRepublic
I'll Make Love To You - Boyz II Men
Burden In My Hand - Soundgarden
Shake Your Groove Thing - Peaches & Herb
Car Wash - Rose Royce
Change - Blind Melon
Mountains - Biffy Clyro
Never As Tired As When I'm Waking Up - LCD Soundsystem
Too Sick To Pray - Phosphorescent
Only One (Live) (Sessions@AOL) - Yellowcard
Secret Love - Mariah Carey
Noc... - Justyna Steczkowska
Sunrise - Yeasayer

In [87]:
ir.recommend(song_df['user_id'][4000])

No. of unique songs for the user: 168
no. of unique songs in the training set: 5151
Non zero values in cooccurence_matrix :45432

,user_id,song,score,rank
0,9b887e10a4711486085c4fae2d2599fc0d2c484d,How It Feels To Fly - Alicia Keys,0.046506,1
1,9b887e10a4711486085c4fae2d2599fc0d2c484d,No One - Alicia Keys,0.038112,2
2,9b887e10a4711486085c4fae2d2599fc0d2c484d,Diary - Alicia Keys featuring Tony! Toni! Ton�...,0.036327,3
3,9b887e10a4711486085c4fae2d2599fc0d2c484d,Secret Love - Mariah Carey,0.035414,4
4,9b887e10a4711486085c4fae2d2599fc0d2c484d,Infatueighties - Musiq,0.033829,5
5,9b887e10a4711486085c4fae2d2599fc0d2c484d,Caught Out There (Explicit) - Kelis,0.033829,6
6,9b887e10a4711486085c4fae2d2599fc0d2c484d,Si Yo Fuera Un Chico - Beyonc�,0.033829,7
7,9b887e10a4711486085c4fae2d2599fc0d2c484d,Danger - Erykah Badu,0.033829,8
8,9b887e10a4711486085c4fae2d2599fc0d2c484d,I Should Be... - Dru Hill,0.033829,9
9,9b887e10a4711486085c4fae2d2599fc0d2c484d,If This Isn't Love - Jennifer Hudson,0.033829,10

In [79]:
ir.get_similar_items(['Oliver James - Fleet Foxes', 'The End - Pearl Jam'])

no. of unique songs in the training set: 5151
Non zero values in cooccurence_matrix :0

  user_id                                               song  score  rank
0                       Nice Weather For Ducks - Lemon Jelly    0.0     1
1          The Irony Of It All (Album Version) - The Streets    0.0     2
2             Officially Missing You (Radio Version) - Tamia    0.0     3
3             On The Road Again (Pigna People Remix) - Telex    0.0     4
4                          What Can Be Safely Written - Nile    0.0     5
5                   Lord I Guess I'll Never Know - The Verve    0.0     6
6          Take Em To Church - Cam'Ron / Juelz Santana / ...    0.0     7
7          This Ain't A Scene_ It's An Arms Race - Fall O...    0.0     8
8                                   Praise You - Fatboy Slim    0.0     9
9                                        Yeah Yeah - Bodyrox    0.0    10

In [90]:
ir.get_similar_items(['Sehr kosmisch - Harmonia'])

no. of unique songs in the training set: 5151
Non zero values in cooccurence_matrix :1172

  user_id                                               song     score  rank
0                                      Secrets - OneRepublic  0.303571     1
1          Dog Days Are Over (Radio Edit) - Florence + Th...  0.303571     2
2                     Just Dance - Lady GaGa / Colby O'Donis  0.280000     3
3                           Somebody To Love - Justin Bieber  0.265306     4
4                                           Marry Me - Train  0.260000     5
5                        Drop The World - Lil Wayne / Eminem  0.244898     6
6                               Use Somebody - Kings Of Leon  0.241379     7
7                                      Alejandro - Lady GaGa  0.240000     8
8                             Fireflies - Charttraxx Karaoke  0.232143     9
9                                    Revelry - Kings Of Leon  0.224138    10

In [26]:
ir.get_similar_items(['Secrets - OneRepublic'])

no. of unique songs in the training set: 5151
Non zero values in cooccurence_matrix :639

  user_id                                               song     score  rank
0                               Use Somebody - Kings Of Leon  0.309524     1
1                                   Sehr kosmisch - Harmonia  0.303571     2
2          Dog Days Are Over (Radio Edit) - Florence + Th...  0.302326     3
3          Lucky (Album Version) - Jason Mraz & Colbie Ca...  0.263158     4
4                        Drop The World - Lil Wayne / Eminem  0.257143     5
5                            OMG - Usher featuring will.i.am  0.243243     6
6                                           Marry Me - Train  0.243243     7
7                             Fireflies - Charttraxx Karaoke  0.238095     8
8              The Only Exception (Album Version) - Paramore  0.212121     9
9                                     Breakeven - The Script  0.200000    10